name: 'Continuous integration'

on: [push, pull_request]

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v4
        with:
          paths_ignore: '["**/README.md"]'
          concurrent_skipping: 'same_content_newer'


  build:
    name: Test build
    runs-on: 'ubuntu-latest'
    environment: "Preview"
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '18'

      - name: 'Checkout Project'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: yarn install --no-progress

      - name: Lint code
        run: yarn lint

      - name: Run unit tests
        run: yarn test
        if: ${{ github.event_name == 'pull_request' }}

      - name: Build project
        run: yarn build
        if: ${{ github.event_name != 'pull_request' }}
